version: '3.8'

services:
  mongo_db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db

  frontend:
    build: ./client
    ports:
      - "5173:5173"

volumes:
  mongo-data:
