apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud
spec:
  selector:
    app: backend  # 👈 matches the deployment's label
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 5000 # Port in container (Node.js app)
  type: NodePort       # Exposes it on a random port on the node

