apiVersion: v1
kind: Service
metadata:
  name: crud-service
  namespace: crud
spec:
  selector:
    app: crud-app  # 👈 matches the deployment's label
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 5000 # Port in container (Node.js app)
  type: NodePort       # Exposes it on a random port on the node

